version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d # Mount folder containing SQL scripts

  dagster:
    build:
      context: ./dagster_project
      dockerfile: docker/Dockerfile
    container_name: dagster
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DAGSTER_HOME=${DAGSTER_HOME}
      - DATABASE_URL=/dagster_pipeline/dagster_pipeline/storage
    volumes:
      - ./dagster_project:/dagster_project/
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_ENV=production
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_SECRET_KEY=your_super_secret_key
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5436
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_data:/app/superset_home
    command: >
      sh -c "
        export FLASK_APP=superset &&
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "

volumes:
  postgres_data:
  superset_data: